### ISSUE TITLE
Add font-info overrides

### ISSUE THREAD

**Issue by signalwerk** [signalwerk/fontfiller#1]
```css
@font-face {
  font-family: ...;
  src: ...;
  ascent-override: 80%;
  descent-override: 20%;
  line-gap-override: 0%;
  ...
}
```
